// تقویم شمسی، ماموریت، XP، Achievement، رویداد، تکرار، پیشنهاد، Migration
const SCHEMA=2,MIG={1:o=>{DB.stores.forEach(s=>o[s]=o[s]||[]);o.schema=2;return o}};
const migrate=o=>{while(o.schema<SCHEMA)o=MIG[o.schema](o);return o};
const JF=new Intl.DateTimeFormat('en-US-u-ca-persian',{year:'numeric',month:'numeric',day:'numeric'});
const jp=d=>{const o={};JF.formatToParts(d).forEach(x=>o[x.type]=x.value);return{y:+String(o.year||o.relatedYear).replace(/\D/g,''),m:+o.month,d:+o.day}};
const MN=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'],fy=n=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const dt=k=>new Date(k+'T12:00'),add=(k,n)=>{const d=dt(k);d.setDate(d.getDate()+n);return iso(d)};
function mstart(y,m){let d=new Date(y+621,2,10+(m-1)*29,12),c=0;while(!(jp(d).y===y&&jp(d).m===m)&&c++<500)d.setDate(d.getDate()+1);while(jp(d).d>1)d.setDate(d.getDate()-1);return iso(d)}
const mlen=(s,m)=>{let i=0;while(jp(dt(add(s,i))).m===m)i++;return i};
const toast=t=>{const e=document.createElement('div');e.className='toast';e.setAttribute('role','status');e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),3500)};
const CAT={'کار':'#5ee0ff','یادگیری':'#9b7bff','خانواده':'#ffb86b','استراحت':'#5ef0b0','آزاد':'#8fa3c7'},KN={task:'کار',ev:'رویداد',rem:'یادآوری',blk:'بلوک',mis:'ماموریت'};
// XP
const xpc=()=>D.settings.find(s=>s.id==='xpc')||{id:'xpc',task:10,habit:5,mission:20,report:5},X=k=>xpc()[k];
const award=async(src,id,a,date)=>{if(!D.xp.find(x=>x.id===src+'-'+id))await DB.put('xp',{id:src+'-'+id,src,amount:a,date})},unaward=async(src,id)=>{const x=D.xp.find(x=>x.id===src+'-'+id);if(x)await DB.del('xp',x.id)};
async function setX(k,v){const c=xpc();c[k]=Math.max(0,+v||0);await save('settings',c)}
// Achievement
const AD=[['t1','اولین کار انجام‌شده',()=>D.tasks.some(t=>t.status==='done')],['t10','۱۰ کار انجام‌شده',()=>D.tasks.filter(t=>t.status==='done').length>=10],['t50','۵۰ کار انجام‌شده',()=>D.tasks.filter(t=>t.status==='done').length>=50],['g1','اولین هدف ساخته شد',()=>D.goals.length>0],['p1','تکمیل اولین پروژه',()=>D.projects.some(p=>D.tasks.some(t=>t.projectId===p.id)&&pp(p)>=1)],['h7','یک عادت: ۷ روز از ۱۴ روز اخیر',()=>D.habits.some(h=>hstat(h).a>=7)],['h30','۳۰ بار ثبت عادت',()=>D.habitLogs.filter(l=>!l.skip&&l.value>0).length>=30],['m1','اولین ماموریت تمام شد',()=>D.missions.some(m=>m.status==='done')],['e7','انرژی ۷ روز ثبت شد',()=>D.energy.length>=7],['i1','اولین درآمد ثبت شد',()=>D.incomeRecords.length>0],['x100','۱۰۰ XP',()=>D.xp.reduce((a,x)=>a+x.amount,0)>=100]];
async function checkAch(){let n=0;for(const[id,t,f]of AD)if(!D.achievements.find(a=>a.id===id)&&f()){await DB.put('achievements',{id,title:t,at:Date.now()});toast('🏆 '+t);n++}if(n){await load();render()}}
const _save=save;save=async(s,v)=>{await _save(s,v);await checkAch()};
async function addAch(){const t=$('#at').value.trim();if(t)await save('achievements',{title:t,custom:1,at:null})}
async function togAch(id){const a=D.achievements.find(x=>x.id===id);a.at=a.at?null:Date.now();if(a.at)toast('🏆 '+a.title);await save('achievements',a)}
// کار: تکرار، ساعت، XP
const nd=t=>{const b=t.due||T;if(t.rep==='daily')return add(b,1);if(t.rep==='weekly')return add(b,7);if(t.rep==='n')return add(b,t.repN||1);const d=dt(b);d.setMonth(d.getMonth()+1);return iso(d)};
tog=async id=>{const t=D.tasks.find(x=>x.id===id),was=t.status==='done';t.status=was?'todo':'done';t.doneAt=was?null:Date.now();fresh=was?null:id;await DB.put('tasks',t);
 if(was)await unaward('task',id);else{await award('task',id,X('task'),T);if(t.rep){const d=nd(t);if(!D.tasks.some(x=>x.title===t.title&&x.due===d))await DB.put('tasks',{title:t.title,pri:t.pri,status:'todo',due:d,subs:(t.subs||[]).map(s=>({t:s.t,d:0})),rep:t.rep,repN:t.repN,goalId:t.goalId,projectId:t.projectId,time:t.time,dur:t.dur})}}
 await load();render();await checkAch()};
addTask=async()=>{const t=$('#tt').value.trim();if(!t)return;const l=$('#tl').value.split(':'),o={title:t,pri:+$('#tp').value,status:'todo',due:$('#td').value||'',subs:[],time:$('#tm').value||''},r=$('#tr').value;
 if(r==='n'){const n=+prompt('هر چند روز؟','2');if(!n)return;o.rep='n';o.repN=n}else if(r)o.rep=r;
 if(l[0]==='p'){o.projectId=l[1];o.goalId=(D.projects.find(p=>p.id===l[1])||{}).goalId}else if(l[0]==='g')o.goalId=l[1];await save('tasks',o)};
const _tv=VIEWS.tasks;VIEWS.tasks=()=>_tv().replace('<button class="btn" style="margin-top:8px" onclick="addTask()">','<div class="row wrap" style="margin-top:8px"><select id="tr" aria-label="تکرار" style="flex:1"><option value="">بدون تکرار</option><option value="daily">روزانه</option><option value="weekly">هفتگی</option><option value="monthly">ماهانه</option><option value="n">هر N روز…</option></select><input id="tm" type="time" aria-label="ساعت" style="flex:1"></div><button class="btn" style="margin-top:8px" onclick="addTask()">');
const _lh=logH;logH=async(id,v)=>{await _lh(id,v);const h=D.habits.find(x=>x.id===id);if(h&&hdone(h,T))await award('habit',id+T,X('habit'),T);else await unaward('habit',id+T);await load();await checkAch()};
const _sr=saveRep;saveRep=async()=>{await _sr();await award('report',T,X('report'),T);await load();await checkAch()};
// رویداد، یادآوری، بلوک زمانی
async function addEv(){const t=$('#et').value.trim();if(!t)return;await save('events',{title:t,kind:$('#ek').value,date:T,time:$('#etm').value,end:$('#een').value,cat:$('#ec').value})}
async function delEv(id){if(confirm('حذف شود؟')){await DB.del('events',id);await load();render()}}
async function sched(id){const t=D.tasks.find(x=>x.id===id),a=prompt('ساعت شروع (مثل 09:30):');if(!a||!/^\d{1,2}:\d\d$/.test(a))return;t.time=a.padStart(5,'0');t.dur=+prompt('مدت (دقیقه):','60')||60;await save('tasks',t)}
const evForm=()=>`<div class="card"><h2>افزودن به ${fmt(T)}</h2><input id="et" placeholder="عنوان" aria-label="عنوان"><div class="row wrap" style="margin-top:8px"><select id="ek" aria-label="نوع" style="flex:1"><option value="event">رویداد</option><option value="reminder">یادآوری</option><option value="block">بلوک زمانی</option></select><select id="ec" aria-label="دسته" style="flex:1">${Object.keys(CAT).map(c=>`<option>${c}</option>`).join('')}</select></div><div class="row" style="margin-top:8px"><input id="etm" type="time" aria-label="شروع"><input id="een" type="time" aria-label="پایان"></div><button class="btn" style="margin-top:8px" onclick="addEv()">افزودن</button></div>`;
function itemsOn(k){const a=[];D.tasks.filter(t=>t.due===k).forEach(t=>a.push({t:t.title,y:'task',time:t.time||'',dur:t.dur||60,done:t.status==='done',id:t.id}));D.events.filter(e=>e.date===k).forEach(e=>a.push({t:e.title,y:e.kind==='block'?'blk':e.kind==='reminder'?'rem':'ev',time:e.time||'',end:e.end,cat:e.cat,id:e.id}));D.missions.filter(m=>m.due===k).forEach(m=>a.push({t:m.title,y:'mis',done:m.status==='done',time:''}));return a.sort((x,y)=>(x.time||'99').localeCompare(y.time||'99'))}
const itRow=x=>`<div class="it"><span class="mut" style="width:44px">${x.time?fa(x.time.replace(':','٫')):''}</span><span class="g ${x.done?'dn':''}">${H(x.t)}</span><span class="tag">${KN[x.y]}</span>${x.y==='task'?`<button class="chk ${x.done?'on':''}" aria-label="تکمیل" onclick="tog('${x.id}')">${x.done?'✓':''}</button>`:['ev','rem','blk'].includes(x.y)?`<button class="ic" aria-label="حذف" onclick="delEv('${x.id}')">🗑</button>`:''}</div>`;
let CV='m';
function stepCal(n){const c=jp(dt(T));if(CV==='m'){const s=mstart(c.y,c.m);T=n<0?add(s,-1):add(s,mlen(s,c.m))}else T=add(T,n*(CV==='w'?7:1));render()}
function cal(){const c=jp(dt(T)),pl=[['m','ماهانه'],['w','هفتگی'],['d','روزانه'],['t','زمان‌بندی']];let b='';
 if(CV==='m'){const s=mstart(c.y,c.m),n=mlen(s,c.m),off=(dt(s).getDay()+1)%7;b='<div class="cg">'+['ش','ی','د','س','چ','پ','ج'].map(x=>`<b>${x}</b>`).join('')+'<span></span>'.repeat(off)+Array.from({length:n},(_,i)=>{const k=add(s,i),m=itemsOn(k).length;return `<button class="cd ${k===T?'on':''} ${k===iso()?'td':''}" aria-label="${fmt(k)}" onclick="T='${k}';CV='d';render()">${fa(i+1)}<i>${'•'.repeat(Math.min(3,m))}</i></button>`}).join('')+'</div>'}
 else if(CV==='w'){const ws=add(T,-((dt(T).getDay()+1)%7));b=Array.from({length:7},(_,i)=>{const k=add(ws,i),a=itemsOn(k);return `<div class="card"><h2 onclick="T='${k}';CV='d';render()">${dt(k).toLocaleDateString('fa-IR',{weekday:'long',day:'numeric',month:'long'})}</h2>${a.map(itRow).join('')||'<div class="mut">خالی</div>'}</div>`}).join('')}
 else if(CV==='d'){const a=itemsOn(T);b=`<div class="card">${a.map(itRow).join('')||'<div class="empty">برای این روز چیزی نیست.</div>'}</div>`+evForm()}
 else{const mins=s=>{const[a,z]=s.split(':');return +a*60+ +z},a=itemsOn(T).filter(x=>x.time),un=D.tasks.filter(t=>t.due===T&&!t.time&&open(t));
  b=`<div class="card"><div class="tl" style="height:${18*44}px">${Array.from({length:19},(_,i)=>`<div class="ln" style="top:${i*44}px"></div><span class="hr" style="top:${i*44-8}px">${fa(i+6)}:۰۰</span>`).join('')}${a.map(x=>{const s=mins(x.time),d=x.end?mins(x.end)-s:(x.dur||60),col=CAT[x.cat]||'#5ee0ff';return `<div class="tb" style="top:${Math.max(0,(s-360)/60*44)}px;height:${Math.max(22,d/60*44)}px;background:${col}33;border-right:3px solid ${col}">${H(x.t)}</div>`}).join('')}</div></div>`+(un.length?`<div class="card"><h2>کارهای بدون ساعت</h2>${un.map(t=>`<div class="it"><span class="g">${H(t.title)}</span><button class="btn o" onclick="sched('${t.id}')">زمان‌بندی</button></div>`).join('')}</div>`:'')+evForm()}
 return `<div class="card"><div class="row"><button class="ic" aria-label="قبلی" onclick="stepCal(-1)">›</button><div class="g big" style="text-align:center">${MN[c.m-1]} ${fy(c.y)}<div class="mut">${fmt(T)}</div></div><button class="ic" aria-label="بعدی" onclick="stepCal(1)">‹</button></div><div class="pills" style="margin-top:8px">${pl.map(([k,v])=>`<button class="${CV===k?'on':''}" onclick="CV='${k}';render()">${v}</button>`).join('')}</div></div>`+b}
// ماموریت‌ها
const MT={simple:'ساده',goal:'هدف‌محور',steps:'چندمرحله‌ای'},mp=m=>m.status==='done'?100:m.type==='goal'?m.prog:m.type==='steps'&&m.steps.length?Math.round(m.steps.filter(s=>s.d).length/m.steps.length*100):0;
async function addMis(){const t=$('#mt').value.trim();if(!t)return;await save('missions',{title:t,type:$('#my').value,scope:$('#ms').value,due:$('#md').value,xp:+$('#mx').value||X('mission'),status:'todo',prog:0,steps:[],goalId:$('#mg').value||null})}
async function misDone(id){const m=D.missions.find(x=>x.id===id),was=m.status==='done';m.status=was?'todo':'done';fresh=was?null:id;await DB.put('missions',m);if(was)await unaward('mission',id);else await award('mission',id,m.xp,T);await load();render();await checkAch()}
async function misStep(id){const s=prompt('عنوان مرحله:');if(!s)return;const m=D.missions.find(x=>x.id===id);m.steps.push({t:s,d:0});await save('missions',m)}
async function misTS(id,i){const m=D.missions.find(x=>x.id===id);m.steps[i].d^=1;await save('missions',m)}
async function misProg(id){const v=prompt('درصد پیشرفت (۰ تا ۱۰۰):');if(v===null)return;const m=D.missions.find(x=>x.id===id);m.prog=Math.max(0,Math.min(100,+v||0));await save('missions',m)}
const misRow=m=>`<div class="card"><div class="row"><button class="chk ${m.status==='done'?'on':''} ${fresh===m.id?'fresh':''}" aria-label="تکمیل ماموریت" onclick="misDone('${m.id}')">${m.status==='done'?'✓':''}</button><div class="g"><b class="${m.status==='done'?'dn':''}">${H(m.title)}</b><div class="mut">${MT[m.type]} · ${m.scope==='daily'?'روزانه':'بلندمدت'}${m.due?' · '+fmt(m.due):''} · ${fa(m.xp)} XP</div></div><button class="ic" aria-label="حذف" onclick="dd('missions','${m.id}','ماموریت حذف شود؟')">🗑</button></div>${m.type!=='simple'?bar(mp(m)/100):''}${m.type==='goal'?`<button class="btn o" style="margin-top:8px" onclick="misProg('${m.id}')">پیشرفت: ${fa(m.prog)}٪</button>`:''}${m.type==='steps'?m.steps.map((s,i)=>`<label class="mut" style="display:block"><input type="checkbox" style="width:auto;min-height:0" ${s.d?'checked':''} onchange="misTS('${m.id}',${i})"> ${H(s.t)}</label>`).join('')+`<button class="btn o" style="margin-top:8px" onclick="misStep('${m.id}')">＋ مرحله</button>`:''}</div>`;
function mis(){const a=D.missions,td=a.filter(m=>m.status!=='done'&&m.scope==='daily'&&(!m.due||m.due===T)),lg=a.filter(m=>m.status!=='done'&&m.scope==='long'),dn=a.filter(m=>m.status==='done');
 return `<div class="card"><h2>ماموریت جدید</h2><input id="mt" placeholder="مثلاً: رزومه را آماده کن" aria-label="عنوان"><div class="row wrap" style="margin-top:8px"><select id="my" aria-label="نوع" style="flex:1">${Object.entries(MT).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><select id="ms" aria-label="دامنه" style="flex:1"><option value="daily">روزانه</option><option value="long">بلندمدت</option></select></div><div class="row" style="margin-top:8px"><input id="md" type="date" value="${T}" aria-label="تاریخ"><input id="mx" type="number" placeholder="XP" aria-label="XP"></div><select id="mg" style="margin-top:8px" aria-label="هدف"><option value="">بدون هدف</option>${D.goals.map(g=>`<option value="${g.id}">${H(g.title)}</option>`).join('')}</select><button class="btn" style="margin-top:8px" onclick="addMis()">افزودن</button></div>`
 +(a.length?'':'<div class="empty">هنوز ماموریتی نداری.</div>')+(td.length?'<h2>امروز</h2>'+td.map(misRow).join(''):'')+(lg.length?'<h2>بلندمدت</h2>'+lg.map(misRow).join(''):'')+(dn.length?'<h2>انجام‌شده</h2>'+dn.map(misRow).join(''):'')}
// XP و Achievement
function xp(){const tot=D.xp.reduce((a,x)=>a+x.amount,0),days=Array.from({length:7},(_,i)=>back(6-i)),v=days.map(k=>D.xp.filter(x=>x.date===k).reduce((a,x)=>a+x.amount,0)),mx=Math.max(1,...v),S={task:'کار',habit:'عادت',mission:'ماموریت',report:'گزارش'};
 return `<div class="card"><div class="big">${fa(tot)} XP</div><div class="mut">فقط نمایشی است و چیزی را قفل یا باز نمی‌کند.</div><div class="row" style="align-items:flex-end;height:70px;margin-top:8px">${v.map((n,i)=>`<div class="g" style="height:100%;display:flex;align-items:flex-end"><i title="${fmt(days[i])}" style="display:block;width:100%;height:${n/mx*100}%;min-height:2px;background:var(--acc);border-radius:4px 4px 0 0"></i></div>`).join('')}</div><div class="mut">۷ روز اخیر</div></div>
<div class="card"><h2>مقدار XP هر فعالیت</h2><div class="row wrap">${Object.entries(S).map(([k,n])=>`<label class="g mut" style="min-width:45%">${n}<input type="number" min="0" value="${X(k)}" onchange="setX('${k}',this.value)"></label>`).join('')}</div></div>
<div class="card"><h2>Achievementها</h2>${AD.map(([id,t])=>{const a=D.achievements.find(x=>x.id===id);return `<div class="it"><span class="g ${a?'':'mut'}">${a?'🏆':'🔒'} ${t}</span>${a?`<span class="mut">${fmt(iso(new Date(a.at)))}</span>`:''}</div>`}).join('')}${D.achievements.filter(a=>a.custom).map(a=>`<div class="it"><button class="chk ${a.at?'on':''}" aria-label="باز شد" onclick="togAch('${a.id}')">${a.at?'✓':''}</button><span class="g">${H(a.title)}</span><button class="ic" aria-label="حذف" onclick="dd('achievements','${a.id}','حذف شود؟')">🗑</button></div>`).join('')}<div class="row" style="margin-top:8px"><input id="at" placeholder="Achievement سفارشی، مثلاً ۱۰ روز ورزش" aria-label="سفارشی"><button class="btn" onclick="addAch()">+</button></div></div>`}
// پیشنهادها (فقط با تأیید کاربر ساخته می‌شوند)
let SG=[];
function sugs(){const s=[],w=Array.from({length:7},(_,i)=>back(i)),e=D.energy.filter(x=>w.includes(x.id)).map(score),has=r=>D.habits.some(h=>r.test(h.title));
 D.goals.filter(g=>gp(g)<1&&!D.tasks.some(t=>open(t)&&t.goalId===g.id)).slice(0,2).forEach(g=>s.push({t:`یک قدم کوچک برای هدف «${g.title}»`,k:'task',v:'قدم بعدی: '+g.title,g:g.id}));
 D.opps.filter(o=>o.status<3&&!D.tasks.some(t=>open(t)&&t.oppId===o.id)).slice(0,2).forEach(o=>s.push({t:`پیگیری فرصت «${o.title}»`,k:'task',v:'پیگیری: '+o.title,o:o.id}));
 if(e.length&&avg(e)<2.5&&!has(/خواب/))s.push({t:'انرژی‌ات پایین بوده؛ عادت «خواب منظم» کمک می‌کند',k:'habit',v:'خواب منظم'});
 if(D.energy.filter(x=>w.includes(x.id)&&x.a[6]===0).length>=3&&!has(/ورزش|پیاده/))s.push({t:'چند روز ورزش نکرده‌ای؛ یک عادت کوچک شروع کن',k:'habit',v:'۱۰ دقیقه پیاده‌روی'});
 if(!D.habits.length)s.push({t:'هنوز عادتی نداری؛ یک عادت خیلی کوچک شروع خوبی است',k:'habit',v:'نوشیدن آب'});return s}
async function accSug(i){const x=SG[i];if(x.k==='habit')await save('habits',{title:x.v,type:'daily',target:1});else await save('tasks',{title:x.v,pri:3,status:'todo',due:T,subs:[],goalId:x.g||null,oppId:x.o||null})}
function sug(){SG=sugs();return `<div class="card"><h2>پیشنهادها</h2><div class="mut">فقط از داده‌ی خودت؛ هیچ‌چیز بدون تأیید تو ساخته نمی‌شود.</div></div>`+(SG.map((x,i)=>`<div class="card row"><span class="g">${H(x.t)}</span><button class="btn" onclick="accSug(${i})">${x.k==='habit'?'ساخت عادت':'ساخت کار'}</button></div>`).join('')||'<div class="empty">فعلاً پیشنهادی نیست.</div>')}
// داشبورد و منو
CARDS.mis='ماموریت‌ها';CD.mis=()=>{const a=D.missions.filter(m=>m.status!=='done'&&(m.scope==='long'||!m.due||m.due===T));return `<h2 onclick="go('mis')">ماموریت‌ها</h2>`+(a.slice(0,3).map(m=>`<div class="mut">${H(m.title)} · ${fa(mp(m))}٪</div>${bar(mp(m)/100)}`).join('')||'<div class="empty">ماموریت فعالی نیست.</div>')};
CARDS.rem='رویداد و یادآوری امروز';CD.rem=()=>{const a=D.events.filter(e=>e.date===T&&e.kind!=='block').sort((x,y)=>(x.time||'99').localeCompare(y.time||'99'));return `<h2 onclick="go('cal')">رویداد و یادآوری امروز</h2>`+(a.map(e=>`<div class="mut">${e.time?fa(e.time.replace(':','٫'))+' · ':''}${H(e.title)}</div>`).join('')||'<div class="empty">چیزی برای امروز نیست.</div>')};
CARDS.xp='XP';CD.xp=()=>`<h2 onclick="go('xp')">XP</h2><div class="big">${fa(D.xp.reduce((a,x)=>a+x.amount,0))}</div>`;
VIEWS.more=()=>`<div class="card"><div class="row wrap">${[['mis','ماموریت‌ها'],['xp','XP و Achievement'],['sug','پیشنهادها'],['inc','درآمد'],['crm','مخاطبین'],['jr','ژورنال'],['rep','گزارش‌ها'],['srch','جست‌وجو'],['en','انرژی'],['ctl','مرکز کنترل']].map(([k,v])=>`<button class="btn o" style="flex:1 0 40%" onclick="go('${k}')">${v}</button>`).join('')}</div></div>`;
Object.assign(VIEWS,{cal,mis,xp,sug});NAV.splice(2,0,['cal','تقویم']);
setInterval(async()=>{const n=new Date(),k=iso(n),hm=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0');for(const e of D.events.filter(e=>e.kind==='reminder'&&e.date===k&&e.time&&e.time<=hm&&!e.fired)){e.fired=1;await DB.put('events',e);toast('⏰ '+e.title)}},20000);
setTimeout(()=>checkAch(),1500);
