// ماژول‌های درآمد، CRM، ژورنال، گزارش‌ها، جست‌وجو
const OS=['جدید','در گفتگو','پیشنهاد','موفق','ناموفق'],MO=['😞','😕','😐','🙂','😄'];let SQ='',SJ='',RP=7;
const pmk=k=>{const o={};new Intl.DateTimeFormat('en-US-u-ca-persian',{year:'numeric',month:'numeric'}).formatToParts(new Date(k+'T12:00')).forEach(x=>o[x.type]=x.value);return String(o.year||o.relatedYear).replace(/\D/g,'')+'/'+o.month};
const dd=async(s,id,m)=>{if(!confirm(m)||!confirm('تأیید دوم: حذف قطعی؟'))return;await DB.del(s,id);await load();render()};
// درآمد
async function addPath(){const t=$('#it').value.trim();if(t)await save('incomePaths',{title:t,target:+$('#ig').value||0,note:''})}
async function addRec(id){const a=+prompt('مبلغ درآمد برای تاریخ انتخاب‌شده:');if(a)await save('incomeRecords',{pathId:id,amount:a,date:T})}
async function addOpp(){const t=$('#ot').value.trim();if(t)await save('opps',{title:t,pathId:$('#op').value||null,contactId:$('#oc').value||null,amount:+$('#oa').value||0,status:0})}
async function cycOpp(id){const o=D.opps.find(x=>x.id===id);o.status=(o.status+1)%5;await save('opps',o)}
async function oppTask(id){const o=D.opps.find(x=>x.id===id);await DB.put('tasks',{title:'پیگیری: '+o.title,pri:4,status:'todo',due:T,subs:[],oppId:id});await load();render()}
async function delPath(id){const o=D.opps.filter(x=>x.pathId===id),r=D.incomeRecords.filter(x=>x.pathId===id);
 if(!confirm(`این مسیر ${fa(o.length)} فرصت و ${fa(r.length)} ثبت درآمد دارد. فرصت‌ها جدا می‌شوند و ثبت‌های درآمد حذف می‌شوند. ادامه؟`)||!confirm('تأیید دوم: حذف قطعی؟'))return;
 for(const x of o){x.pathId=null;await DB.put('opps',x)}for(const x of r)await DB.del('incomeRecords',x.id);await DB.del('incomePaths',id);await load();render()}
function inc(){const m=pmk(T),sel=(a,t)=>`<option value="">${t}</option>`+a.map(x=>`<option value="${x.id}">${H(x.title||x.name)}</option>`).join('');
 return `<div class="card"><h2>مسیر درآمد جدید</h2><div class="row"><input id="it" placeholder="مثلاً فریلنسری" aria-label="عنوان مسیر"><input id="ig" type="number" placeholder="هدف ماهانه" aria-label="هدف ماهانه"></div><button class="btn" style="margin-top:8px" onclick="addPath()">افزودن مسیر</button></div>`
 +(D.incomePaths.length?'':'<div class="empty">هنوز مسیر درآمدی نداری. اولین مسیر را بساز.</div>')
 +D.incomePaths.map(p=>{const s=D.incomeRecords.filter(r=>r.pathId===p.id&&pmk(r.date)===m).reduce((a,r)=>a+r.amount,0);return `<div class="card"><div class="row"><b class="g">${H(p.title)}</b><button class="ic" aria-label="حذف مسیر" onclick="delPath('${p.id}')">🗑</button></div><div class="mut">این ماه: ${fa(s)}${p.target?' از '+fa(p.target)+' · فاصله: '+fa(Math.max(0,p.target-s)):''}</div>${p.target?bar(Math.min(1,s/p.target)):''}<button class="btn o" style="margin-top:8px" onclick="addRec('${p.id}')">ثبت درآمد</button>${D.opps.filter(o=>o.pathId===p.id).map(o=>`<div class="it"><div class="g">${H(o.title)}<div class="mut">${o.amount?fa(o.amount):''}</div></div><button class="tag" onclick="cycOpp('${o.id}')">${OS[o.status]}</button><button class="ic" aria-label="ساخت کار" onclick="oppTask('${o.id}')">＋کار</button><button class="ic" aria-label="حذف" onclick="dd('opps','${o.id}','فرصت حذف شود؟')">🗑</button></div>`).join('')}</div>`}).join('')
 +`<div class="card"><h2>فرصت جدید</h2><input id="ot" placeholder="عنوان فرصت" aria-label="فرصت"><div class="row wrap" style="margin-top:8px"><select id="op" aria-label="مسیر">${sel(D.incomePaths,'بدون مسیر')}</select><select id="oc" aria-label="مخاطب">${sel(D.contacts,'بدون مخاطب')}</select><input id="oa" type="number" placeholder="مبلغ احتمالی" aria-label="مبلغ"></div><button class="btn" style="margin-top:8px" onclick="addOpp()">افزودن فرصت</button></div>`}
// CRM
let SC='';
async function addCt(){const n=$('#cn').value.trim();if(n)await save('contacts',{name:n,phone:$('#cp').value.trim(),org:$('#co').value.trim(),note:'',hist:[],last:'',next:''})}
async function callCt(id){const c=D.contacts.find(x=>x.id===id),n=prompt('خلاصه‌ی تعامل:');if(n===null)return;c.last=T;c.hist.push({d:T,t:n});await save('contacts',c)}
async function nextCt(id){const c=D.contacts.find(x=>x.id===id),n=prompt('تاریخ تماس بعدی (مثل 2026-10-20):',c.next||T);if(n===null)return;c.next=n;await save('contacts',c)}
function crm(){const q=SC.toLowerCase(),a=D.contacts.filter(c=>(c.name+' '+c.org+' '+c.note+' '+c.phone).toLowerCase().includes(q));
 return `<div class="card"><h2>مخاطب جدید</h2><div class="row wrap"><input id="cn" placeholder="نام" aria-label="نام"><input id="cp" placeholder="شماره" aria-label="شماره" inputmode="tel"><input id="co" placeholder="مجموعه" aria-label="مجموعه"></div><button class="btn" style="margin-top:8px" onclick="addCt()">افزودن</button></div><input value="${H(SC)}" placeholder="جست‌وجو در مخاطبین (Enter)" aria-label="جست‌وجو" style="margin-bottom:12px" onchange="SC=this.value;render()">`
 +(a.length?a.map(c=>`<div class="card"><div class="row"><b class="g">${H(c.name)}</b><button class="ic" aria-label="حذف" onclick="dd('contacts','${c.id}','مخاطب و تاریخچه‌اش حذف شود؟')">🗑</button></div><div class="mut">${H(c.org)} ${c.phone?'· '+H(c.phone):''}<br>آخرین تماس: ${c.last?fmt(c.last):'—'} · بعدی: ${c.next?fmt(c.next):'—'}</div>${c.hist.slice(-3).map(h=>`<div class="mut">• ${fmt(h.d)}: ${H(h.t)}</div>`).join('')}<div class="row" style="margin-top:8px"><button class="btn o" onclick="callCt('${c.id}')">ثبت تعامل</button><button class="btn o" onclick="nextCt('${c.id}')">تماس بعدی</button></div></div>`).join(''):'<div class="empty">مخاطبی نیست.</div>')}
// ژورنال
async function addJr(){const t=$('#jt').value.trim();if(t)await save('journal',{text:t,mood:+$('#jm').value,tag:$('#jg').value.trim(),date:T})}
function jr(){const q=SJ.toLowerCase(),a=D.journal.filter(j=>q?(j.text+' '+j.tag).toLowerCase().includes(q):j.date===T).sort((x,y)=>y.created-x.created);
 return `<div class="card"><h2>یادداشت ${fmt(T)}</h2><textarea id="jt" rows="4" placeholder="امروز چه گذشت؟" aria-label="متن"></textarea><div class="row" style="margin-top:8px"><select id="jm" aria-label="حال">${MO.map((m,i)=>`<option value="${i+1}" ${i===3?'selected':''}>${m}</option>`).join('')}</select><input id="jg" placeholder="برچسب" aria-label="برچسب"></div><button class="btn" style="margin-top:8px" onclick="addJr()">ذخیره</button></div><input value="${H(SJ)}" placeholder="جست‌وجو در همه‌ی ژورنال (Enter؛ خالی = همین روز)" aria-label="جست‌وجو" style="margin-bottom:12px" onchange="SJ=this.value;render()">`
 +(a.map(j=>`<div class="card"><div class="row"><span class="g mut">${fmt(j.date)} ${MO[j.mood-1]} ${j.tag?'<span class="tag">'+H(j.tag)+'</span>':''}</span><button class="ic" aria-label="حذف" onclick="dd('journal','${j.id}','یادداشت حذف شود؟')">🗑</button></div><div style="white-space:pre-wrap">${H(j.text)}</div></div>`).join('')||'<div class="empty">یادداشتی نیست.</div>')}
// گزارش‌ها
const dayk=(n,i)=>Array.from({length:RP},(_,j)=>back(j+i*RP));
const doneIn=k=>D.tasks.filter(t=>t.doneAt&&k.includes(iso(new Date(t.doneAt)))).length,habIn=k=>D.habitLogs.filter(l=>k.includes(l.date)&&!l.skip&&l.value>0).length,
enIn=k=>{const a=D.energy.filter(e=>k.includes(e.id)).map(score);return a.length?avg(a):0},incIn=k=>D.incomeRecords.filter(r=>k.includes(r.date)).reduce((s,r)=>s+r.amount,0);
async function saveRep(){await DB.put('reports',{id:'d-'+T,text:$('#rt').value});await load();alert('ذخیره شد')}
function mkPrompt(){const c=dayk(0,0),p=dayk(0,1);return `تو یک مربی و تحلیل‌گر عملکرد هستی. داده‌های ${fa(RP)} روز اخیر من (در پرانتز: دوره‌ی قبل):\n- کارهای انجام‌شده: ${fa(doneIn(c))} (${fa(doneIn(p))})\n- ثبت عادت‌ها: ${fa(habIn(c))} (${fa(habIn(p))})\n- میانگین انرژی از ۵: ${fa(enIn(c).toFixed(1))} (${fa(enIn(p).toFixed(1))})\n- درآمد ثبت‌شده: ${fa(incIn(c))} (${fa(incIn(p))})\n- کارهای عقب‌افتاده: ${fa(D.tasks.filter(t=>open(t)&&t.due&&t.due<iso()).length)}\n- اهداف: ${D.goals.map(g=>g.title+' '+Math.round(gp(g)*100)+'٪').join('، ')||'—'}\n- مسیرهای درآمد: ${D.incomePaths.map(p=>p.title).join('، ')||'—'}\n- فرصت‌ها: ${D.opps.map(o=>o.title+' ('+OS[o.status]+')').join('، ')||'—'}\nلطفاً: ۱) نقاط قوت ۲) موانع احتمالی ۳) حداکثر سه پیشنهاد مشخص برای دوره‌ی بعد. فقط پیشنهاد بده؛ چیزی را خودسرانه تغییر نده و اگر داده کم است بگو.`}
function rep(){const c=dayk(0,0),p=dayk(0,1),od=D.tasks.filter(t=>open(t)&&t.due&&t.due<iso()).length,r=D.reports.find(x=>x.id==='d-'+T),tips=[];
 if(enIn(c)&&enIn(c)<2.5)tips.push('میانگین انرژی پایین بوده؛ یک تغییر کوچک در خواب یا حرکت امتحان کن.');if(od>=3)tips.push(fa(od)+' کار عقب‌افتاده داری؛ فقط یکی را تعیین تکلیف کن.');if(D.incomePaths.length&&!incIn(c))tips.push('در این دوره درآمدی ثبت نشده؛ یک پیگیری از فرصت‌ها را کار امروز کن.');if(!tips.length)tips.push('روند پایدار است؛ همین ریتم را نگه دار.');
 const L=(n,a,b)=>`<div class="it"><span class="g">${n}</span><b>${fa(a)}</b><span class="mut">(${fa(b)})</span></div>`,dt=D.tasks.filter(t=>t.due===T);
 return `<div class="card"><h2>گزارش ${fmt(T)}</h2>${L('کار انجام‌شده',D.tasks.filter(t=>t.doneAt&&iso(new Date(t.doneAt))===T).length,0)}${L('کار انجام‌نشده برای این روز',dt.filter(open).length,0)}${L('عادت‌های ثبت‌شده',habIn([T]),0)}${L('انرژی',score(er()).toFixed(1),0)}${L('درآمد',incIn([T]),0)}<textarea id="rt" rows="3" placeholder="امروز چه گذشت؟" aria-label="متن گزارش" style="margin-top:8px">${H(r?r.text:'')}</textarea><button class="btn" style="margin-top:8px" onclick="saveRep()">ذخیره‌ی گزارش</button></div>
<div class="card"><div class="pills">${[7,30].map(n=>`<button class="${RP===n?'on':''}" onclick="RP=${n};render()">${n===7?'هفتگی':'ماهانه'}</button>`).join('')}</div><h2 style="margin-top:10px">${fa(RP)} روز اخیر (دوره‌ی قبل)</h2>${L('کار انجام‌شده',doneIn(c),doneIn(p))}${L('ثبت عادت',habIn(c),habIn(p))}${L('میانگین انرژی',enIn(c).toFixed(1),enIn(p).toFixed(1))}${L('درآمد',incIn(c),incIn(p))}${L('عقب‌افتاده (الان)',od,0)}<div class="row" style="align-items:flex-end;height:70px;margin-top:8px">${c.slice().reverse().map(k=>{const n=doneIn([k]);return `<div class="g" style="height:100%;display:flex;align-items:flex-end"><i style="display:block;width:100%;height:${Math.min(100,n*20)}%;min-height:2px;background:var(--acc);border-radius:4px 4px 0 0" title="${fmt(k)}"></i></div>`}).join('')}</div><div class="mut">کارهای انجام‌شده در هر روز</div></div>
<div class="card"><h2>تحلیل (فقط پیشنهاد)</h2>${tips.map(t=>`<div class="mut">• ${t}</div>`).join('')}<button class="btn o" style="margin-top:8px" onclick="$('#pr').value=mkPrompt();$('#pr').hidden=false;$('#cp2').hidden=false">ساخت پرامپت برای AI</button><textarea id="pr" rows="8" hidden aria-label="پرامپت"></textarea><button id="cp2" class="btn" hidden style="margin-top:8px" onclick="navigator.clipboard.writeText($('#pr').value).then(()=>alert('کپی شد'))">کپی پرامپت</button></div>`}
// جست‌وجو و بیشتر
function srch(){const q=SQ.trim().toLowerCase(),m=(...a)=>a.join(' ').toLowerCase().includes(q);const G=[['کارها',D.tasks.filter(t=>m(t.title)),t=>t.title,'tasks'],['اهداف',D.goals.filter(g=>m(g.title)),g=>g.title,'goals'],['پروژه‌ها',D.projects.filter(p=>m(p.title)),p=>p.title,'goals'],['عادت‌ها',D.habits.filter(h=>m(h.title)),h=>h.title,'hab'],['ژورنال',D.journal.filter(j=>m(j.text,j.tag)),j=>j.text.slice(0,60),'jr'],['مخاطبین',D.contacts.filter(c=>m(c.name,c.org,c.note)),c=>c.name,'crm'],['فرصت‌ها',D.opps.filter(o=>m(o.title)),o=>o.title,'inc'],['مسیر درآمد',D.incomePaths.filter(p=>m(p.title)),p=>p.title,'inc'],['گزارش‌ها',D.reports.filter(r=>m(r.text)),r=>r.text.slice(0,60),'rep']];
 return `<input value="${H(SQ)}" placeholder="جست‌وجو در همه‌چیز (Enter)" aria-label="جست‌وجوی سراسری" style="margin-bottom:12px" onchange="SQ=this.value;render()">`+(q?(G.map(([h,a,f,v])=>a.length?`<div class="card"><h2>${h}</h2>${a.map(x=>`<div class="it"><button class="ic g" style="text-align:right" onclick="go('${v}')">${H(f(x))}</button></div>`).join('')}</div>`:'').join('')||'<div class="empty">نتیجه‌ای نیست.</div>'):'')}
function more(){return `<div class="card"><div class="row wrap">${[['inc','درآمد'],['crm','مخاطبین'],['jr','ژورنال'],['rep','گزارش‌ها'],['srch','جست‌وجو'],['en','انرژی'],['ctl','مرکز کنترل']].map(([k,v])=>`<button class="btn o" style="flex:1 0 40%" onclick="go('${k}')">${v}</button>`).join('')}</div></div>`}
Object.assign(VIEWS,{more,inc,crm,jr,rep,srch});
CARDS.inc='درآمد این ماه';CD.inc=()=>{const m=pmk(T),s=D.incomeRecords.filter(r=>pmk(r.date)===m).reduce((a,r)=>a+r.amount,0),t=D.incomePaths.reduce((a,p)=>a+p.target,0);return `<h2 onclick="go('inc')">درآمد این ماه</h2>${D.incomePaths.length?`<div class="mut">${fa(s)}${t?' از '+fa(t):''}</div>${t?bar(Math.min(1,s/t)):''}`:'<div class="empty">هنوز مسیر درآمدی نداری.</div>'}`};
