// طراحی جدید، عادت‌های پیشرفته، هدف عددی، موعد یکپارچه، یادآوری قاعده‌مند، برچسب، روند
const nz=s=>String(s||'').replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/،/g,',').trim();
const IC={dash:'M3 11l9-8 9 8v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z',tasks:'M5 7l2 2 3-3M5 15l2 2 3-3M13 8h7M13 16h7',cal:'M4 7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2zM4 10h16M9 3v4M15 3v4',goals:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zM12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8z',more:'M6 12h.01M12 12h.01M18 12h.01'};
const ico=k=>`<svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${IC[k]}"/></svg>`;
NAV.length=0;NAV.push(['tasks','کارها'],['cal','تقویم'],['dash','خانه'],['goals','اهداف'],['more','بیشتر']);
const _r=render;render=()=>{_r();document.documentElement.dataset.glow=cfg().glow===0?'off':'on';$('#nav').innerHTML=NAV.map(([k,v])=>`<button class="${ON(k)?'on':''} ${k==='dash'?'ctr':''}" ${ON(k)?'aria-current="page"':''} onclick="go('${k}')">${ico(k)}<span>${v}</span></button>`).join('')};
const _c=VIEWS.ctl;VIEWS.ctl=()=>{const c=cfg();return _c().replace('<label class="row" style="margin-top:8px">',`<label class="row" style="margin-top:8px"><input type="checkbox" style="width:auto;min-height:0" ${c.glow===0?'':'checked'} onchange="setCfg(c=>c.glow=this.checked?1:0)"> جلوه‌های نورانی و شیشه‌ای</label><label class="row" style="margin-top:8px">`)};
// برچسب و فیلتر
let TG='';const tags=()=>[...new Set([...D.tasks,...D.habits].map(x=>x.tag).filter(Boolean))];
const chips=()=>tags().length?`<div class="chips" role="group" aria-label="فیلتر برچسب"><button class="${TG?'':'on'}" onclick="TG='';render()">همه</button>${tags().map(t=>`<button class="${TG===t?'on':''}" data-t="${H(t)}" onclick="TG=this.dataset.t;render()">${H(t)}</button>`).join('')}</div>`:'';
const _tk=VIEWS.tasks;VIEWS.tasks=()=>{const b=D.tasks;if(TG)D.tasks=b.filter(t=>t.tag===TG);const h=_tk();D.tasks=b;return chips()+h.replace('<button class="btn" style="margin-top:8px" onclick="addTask()">','<input id="tg" placeholder="برچسب (اختیاری)" aria-label="برچسب" style="margin-top:8px"><button class="btn" style="margin-top:8px" onclick="addTask()">')};
const _at=addTask;addTask=async()=>{const t=$('#tt').value.trim(),tg=($('#tg')||{value:''}).value.trim();await _at();if(tg){const x=D.tasks.filter(y=>y.title===t).sort((a,b)=>b.created-a.created)[0];if(x){x.tag=tg;await save('tasks',x)}}};
// عادت‌ها: رد، محدودکننده، دوره، میانگین، یادداشت
const HP={day:'روزانه',week:'هفتگی',month:'ماهانه',season:'فصلی',year:'سالانه'},HT2={daily:'انجام شد/نشد',count:'تعدادی',minutes:'دقیقه',avg:'عدد میانگین',limit:'محدودکننده'};
const pkey=(p,k)=>{const d=dt(k),j=jp(d);return p==='week'?add(k,-((d.getDay()+1)%7)):p==='month'?j.y+'/'+j.m:p==='season'?j.y+'q'+Math.ceil(j.m/3):p==='year'?String(j.y):k};
const HL=(h,k)=>D.habitLogs.find(l=>l.id===h.id+'_'+k),okLog=(h,l)=>!!l&&!l.skip&&l.value>=(h.type==='daily'?1:(h.target||1));
hdone=(h,k)=>{if(h.type==='limit')return false;if(!h.per||h.per==='day')return okLog(h,HL(h,k));const p=pkey(h.per,k);return D.habitLogs.some(l=>l.habitId===h.id&&okLog(h,l)&&pkey(h.per,l.date)===p)};
hstat=h=>{if(h.per&&h.per!=='day'){const seen=[],ks=[];for(let i=0;i<400&&seen.length<6;i++){const k=back(i),p=pkey(h.per,k);if(!seen.includes(p)){seen.push(p);ks.push(k)}}const a=ks.filter(k=>hdone(h,k)).length;return{a,n:ks.length,sk:0,s:a,m:null}}
 let a=0,sk=0,s=0,m=0,vs=[];for(let i=0;i<14;i++){const k=back(i),l=HL(h,k);if(l&&l.skip)sk++;else if(hdone(h,k))a++;if(l&&!l.skip&&l.value>0)vs.push(l.value)}
 for(let i=0;i<365;i++){const l=HL(h,back(i));if(l&&l.skip)continue;if(hdone(h,back(i))){s++;m=0}else if(i>0){m++;if(m>1)break}}return{a,n:14-sk,sk,s,m:vs.length?avg(vs):null}};
const weekUsed=(h,k)=>D.habitLogs.filter(l=>l.habitId===h.id&&!l.skip&&pkey('week',l.date)===pkey('week',k)).reduce((a,l)=>a+l.value,0);
logH=async(id,v)=>{const h=D.habits.find(x=>x.id===id),o=HL(h,T);if(!v){if(o)await DB.del('habitLogs',o.id)}else await DB.put('habitLogs',{...(o||{}),id:id+'_'+T,habitId:id,date:T,value:v,skip:0});await load();if(hdone(h,T))await award('habit',id+T,X('habit'),T);else await unaward('habit',id+T);await load();render();await checkAch()};
async function skipH(id){const h=D.habits.find(x=>x.id===id),o=HL(h,T);if(o&&o.skip)await DB.del('habitLogs',o.id);else await DB.put('habitLogs',{id:id+'_'+T,habitId:id,date:T,value:0,skip:1});await unaward('habit',id+T);await load();render()}
async function noteH(id){const h=D.habits.find(x=>x.id===id),o=HL(h,T),n=prompt('یادداشت:',o&&o.note||'');if(n===null)return;await DB.put('habitLogs',{value:0,skip:0,...(o||{}),id:id+'_'+T,habitId:id,date:T,note:n});await load();render()}
async function limH(id,d){const h=D.habits.find(x=>x.id===id),o=HL(h,T);await DB.put('habitLogs',{...(o||{}),id:id+'_'+T,habitId:id,date:T,skip:0,value:Math.max(0,(o?o.value:0)+d)});await load();render()}
async function capH(id){const h=D.habits.find(x=>x.id===id),n=+nz(prompt('سقف جدید در هفته:',h.target));if(n>=0){h.target=n;await save('habits',h)}}
addHab=async()=>{const t=$('#ht').value.trim();if(!t)return;const ty=$('#hy').value;await save('habits',{title:t,type:ty,target:+nz($('#hg').value)||1,per:ty==='limit'?'week':$('#hp').value,tag:$('#hq').value.trim(),...linkOf($('#hl').value)})};
const habRow2=h=>{const l=HL(h,T),sk=l&&l.skip,s=hstat(h),d=hdone(h,T),del=`<button class="ic" aria-label="حذف" onclick="delHab('${h.id}')">🗑</button>`;
 if(h.type==='limit'){const u=weekUsed(h,T),over=u>h.target;return `<div class="it" style="display:block"><div class="row"><b class="g">${H(h.title)}</b><span class="tag">محدودکننده</span>${del}</div><div class="bar"><i style="width:${Math.max(0,1-u/h.target)*100}%;background:${over?'#e5484d':'var(--ok)'}"></i></div><div class="mut">${fa(u)} از سقف ${fa(h.target)} در این هفته${over?' · از سقف گذشته‌ای':''}</div><div class="row wrap" style="margin-top:6px"><button class="btn o" onclick="limH('${h.id}',1)">＋۱ امروز</button><button class="btn o" onclick="limH('${h.id}',-1)">−۱</button><button class="btn o" onclick="capH('${h.id}')">تغییر سقف</button></div>${linkSel(h)}</div>`}
 const st=!h.per||h.per==='day'?`${fa(s.a)} از ${fa(s.n)} روز اخیر${s.sk?' ('+fa(s.sk)+' رد شده)':''}${s.m!=null&&h.type!=='daily'?' · میانگین '+fa(s.m.toFixed(1)):''}${s.s>1?' · تداوم '+fa(s.s):''}`:`${fa(s.a)} از ${fa(s.n)} دوره‌ی اخیر (${HP[h.per]})`;
 return `<div class="it"><div class="g"><div class="${sk?'mut':''}">${H(h.title)} ${d?'✓':''}${sk?' · رد شد':''} ${h.tag?'<span class="tag">'+H(h.tag)+'</span>':''}</div><div class="mut">${st}</div>${l&&l.note?`<div class="mut">یادداشت: ${H(l.note)}</div>`:''}<div><button class="ic" style="font-size:13px" onclick="skipH('${h.id}')">${sk?'لغو رد':'رد کردن'}</button><button class="ic" style="font-size:13px" onclick="noteH('${h.id}')">یادداشت</button></div>${linkSel(h)}</div>${h.type==='daily'?`<button class="chk ${d?'on':''}" aria-label="ثبت ${H(h.title)}" onclick="logH('${h.id}',${d?0:1})">${d?'✓':''}</button>`:`<input type="number" min="0" style="width:84px" aria-label="مقدار" value="${l&&!l.skip?l.value:''}" placeholder="/${fa(h.target)}" onchange="logH('${h.id}',+nz(this.value))">`}${del}</div>`};
VIEWS.hab=()=>chips()+`<div class="card"><h2>عادت جدید</h2><input id="ht" placeholder="نام عادت" aria-label="نام عادت"><div class="row wrap" style="margin-top:8px"><select id="hy" style="flex:1" aria-label="نوع">${Object.entries(HT2).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><select id="hp" style="flex:1" aria-label="دوره">${Object.entries(HP).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div class="row" style="margin-top:8px"><input id="hg" type="number" min="1" placeholder="هدف عددی یا سقف" aria-label="هدف"><input id="hq" placeholder="برچسب" aria-label="برچسب"></div><select id="hl" aria-label="ارتباط با هدف یا پروژه" style="margin-top:8px">${linkOpts('')}</select><button class="btn" style="margin-top:8px" onclick="addHab()">افزودن</button></div><div class="card"><h2>عادت‌های ${fmt(T)}</h2>${D.habits.filter(h=>!TG||h.tag===TG).map(habRow2).join('')||'<div class="empty">هنوز عادتی نساخته‌ای.</div>'}</div>`;
// هدف عددی، پیش‌بینی، شمارش معکوس
const proj=(cur,tg,st,en)=>{const days=Math.max(1,(dt(T)-dt(st))/864e5),rate=cur/days,left=Math.max(0,tg-cur),ln=Math.max(1,Math.ceil((dt(en)-dt(T))/864e5));return{need:left/ln,eta:rate>0&&left>0?add(T,Math.ceil(left/rate)):null}};
addGoal=async()=>{const t=$('#gt').value.trim();if(!t)return;await save('goals',{title:t,due:$('#gd').value||'',tv:+nz($('#gv').value)||0,unit:$('#gu').value.trim(),cur:0,start:T})};
async function addVal(id){const v=+nz(prompt('مقدار جدید (به مقدار فعلی اضافه می‌شود):'));if(!v)return;const g=D.goals.find(x=>x.id===id);g.cur=(g.cur||0)+v;await save('goals',g)}
const numCard=()=>{const a=D.goals.filter(g=>g.tv||g.due);return a.length?`<div class="card"><h2>مهلت و پیشرفت عددی</h2>`+a.map(g=>{const left=g.due?Math.ceil((dt(g.due)-dt(T))/864e5):null;let s='';if(g.tv){const p=g.due?proj(g.cur||0,g.tv,g.start||T,g.due):null;s=`<div class="mut">${fa(g.cur||0)} از ${fa(g.tv)} ${H(g.unit||'')}${p?' · لازم: روزی '+fa(p.need.toFixed(1)):''}${p&&p.eta?' · با روند فعلی تا '+fmt(p.eta):''}</div>${bar(Math.min(1,(g.cur||0)/g.tv))}<button class="btn o" style="margin-top:6px" onclick="addVal('${g.id}')">ثبت مقدار</button>`}return `<div class="it" style="display:block"><b>${H(g.title)}</b>${left!==null?` <span class="tag">${left>=0?fa(left)+' روز مانده':'مهلت گذشته'}</span>`:''}${s}</div>`}).join('')+'</div>':''};
const _g=VIEWS.goals;VIEWS.goals=()=>_g().replace('<button class="btn" style="margin-top:8px" onclick="addGoal()">','<div class="row" style="margin-top:8px"><input id="gv" type="number" placeholder="هدف عددی (اختیاری)" aria-label="هدف عددی"><input id="gu" placeholder="واحد" aria-label="واحد" style="max-width:90px"></div><button class="btn" style="margin-top:8px" onclick="addGoal()">')+numCard();
const incProj=()=>{const j=jp(dt(T)),len=mlen(mstart(j.y,j.m),j.m),ps=D.incomePaths.filter(p=>p.target);return ps.length?`<div class="card"><h2>پیش‌بینی همین ماه</h2>`+ps.map(p=>{const s=D.incomeRecords.filter(r=>r.pathId===p.id&&pmk(r.date)===pmk(T)).reduce((a,r)=>a+r.amount,0),pr=s/j.d*len,rem=Math.max(1,len-j.d);return `<div class="it" style="display:block"><b>${H(p.title)}</b><div class="mut">با روند فعلی تا آخر ماه: ${fa(Math.round(pr))} (${pr>=p.target?'به هدف می‌رسی':'کمتر از هدف'}) · برای رسیدن به هدف، روزی ${fa(Math.round(Math.max(0,p.target-s)/rem))}</div>${bar(Math.min(1,s/p.target))}</div>`}).join('')+'</div>':''};
const _i=VIEWS.inc;VIEWS.inc=()=>_i()+incProj();
// یادآوری قاعده‌مند
const remOn=(e,k)=>{if(k<e.date)return false;const d=dt(k),w=(d.getDay()+1)%7,j=jp(d),v=e.rv||'';if(e.rr==='daily')return true;if(e.rr==='week')return v.split(',').map(Number).includes(w);if(e.rr==='nth'){const[n,wd]=v.split(':').map(Number);return w===wd&&Math.ceil(j.d/7)===n}if(e.rr==='last')return jp(dt(add(k,1))).m!==j.m;if(e.rr==='after')return k>=add(e.ld||e.date,+v||1);return false};
itemsOn=k=>{const a=[];D.tasks.filter(t=>t.due===k).forEach(t=>a.push({t:t.title,y:'task',time:t.time||'',dur:t.dur||60,done:t.status==='done',id:t.id}));D.events.filter(e=>e.kind==='rrem'?remOn(e,k):e.date===k).forEach(e=>a.push({t:e.title,y:e.kind==='block'?'blk':e.kind==='event'?'ev':'rem',time:(e.time||'').split(',')[0],end:e.end,cat:e.cat,id:e.id,rr:e.rr}));D.missions.filter(m=>m.due===k).forEach(m=>a.push({t:m.title,y:'mis',done:m.status==='done',time:''}));return a.sort((x,y)=>(x.time||'99').localeCompare(y.time||'99'))};
addEv=async()=>{const t=$('#et').value.trim();if(!t)return;const o={title:t,kind:$('#ek').value,date:T,time:$('#etm').value,end:$('#een').value,cat:$('#ec').value},rr=$('#rr').value;if(rr&&o.kind==='reminder'){o.kind='rrem';o.rr=rr;o.rv=nz($('#rv').value);o.time=nz($('#rt2').value)||o.time}await save('events',o)};
const _cal=VIEWS.cal;VIEWS.cal=()=>_cal().replace('<button class="btn" style="margin-top:8px" onclick="addEv()">','<div class="mut" style="margin-top:8px">تکرار (فقط برای «یادآوری»)</div><select id="rr" aria-label="تکرار"><option value="">بدون تکرار</option><option value="daily">هر روز</option><option value="week">روزهای هفته</option><option value="nth">n‌امین روز هفته‌ی ماه</option><option value="last">آخر ماه</option><option value="after">N روز بعد از آخرین انجام</option></select><input id="rv" placeholder="مقدار: روزهای هفته 0=شنبه…6=جمعه (مثل 0,2) · یا 2:4 = دوشنبه‌ی دوم … · یا N" aria-label="مقدار تکرار" style="margin-top:6px"><input id="rt2" placeholder="چند ساعت در روز، مثل 08:00,20:00" aria-label="ساعت‌ها" style="margin-top:6px"><button class="btn" style="margin-top:8px" onclick="addEv()">');
async function remDone(id){const e=D.events.find(x=>x.id===id);e.ld=T;await save('events',e)}
CD.rem=()=>{const a=itemsOn(T).filter(x=>x.y==='rem'||x.y==='ev');return `<h2 onclick="go('cal')">رویداد و یادآوری امروز</h2>`+(a.map(x=>`<div class="row"><span class="g mut">${x.time?fa(x.time.replace(':','٫'))+' · ':''}${H(x.t)}</span>${x.rr==='after'?`<button class="btn o" onclick="remDone('${x.id}')">انجام شد</button>`:''}</div>`).join('')||'<div class="empty">چیزی برای امروز نیست.</div>')};
setInterval(async()=>{const n=new Date(),k=iso(n),hm=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0');for(const e of D.events.filter(e=>e.kind==='rrem'&&remOn(e,k))){const ts=(e.time||'').split(',').map(s=>s.trim()).filter(Boolean);if(e.fd!==k){e.fd=k;e.ft=[]}for(const t of ts)if(t<=hm&&!e.ft.includes(t)){e.ft.push(t);await DB.put('events',e);toast('⏰ '+e.title)}}},20000);
// موعد یکپارچه و صفحه‌ی خانه
const dueItems=()=>{const a=[];D.tasks.filter(t=>t.due===T).forEach(t=>a.push({n:t.title,d:t.status==='done',f:`tog('${t.id}')`,k:'کار'}));D.habits.filter(h=>h.type!=='limit'&&!(HL(h,T)||{}).skip).forEach(h=>{const d=hdone(h,T),dl=h.type==='daily';a.push({n:h.title,d,f:dl?`logH('${h.id}',${d?0:1})`:`go('hab')`,b:dl?'':'ثبت مقدار',k:'عادت'})});D.missions.filter(m=>m.due===T||(m.scope==='daily'&&!m.due&&m.status!=='done')).forEach(m=>a.push({n:m.title,d:m.status==='done',f:`misDone('${m.id}')`,k:'ماموریت'}));return a};
VIEWS.due=()=>`<div class="card"><h2>موعد ${fmt(T)}</h2>${dueItems().map(x=>`<div class="it"><button class="chk ${x.d?'on':''}" aria-label="تکمیل" onclick="${x.f}">${x.d?'✓':''}</button><span class="g ${x.d?'dn':''}">${H(x.n)}</span><span class="tag">${x.k}</span></div>`).join('')||'<div class="empty">برای این روز چیزی نیست.</div>'}</div>`;
const ringSVG=(p,col,t)=>`<svg viewBox="0 0 80 80" width="88" height="88" role="img" aria-label="${t}"><circle cx="40" cy="40" r="32" fill="none" stroke="rgba(127,150,200,.25)" stroke-width="7"/><circle cx="40" cy="40" r="32" fill="none" stroke="${col}" stroke-width="7" stroke-linecap="round" stroke-dasharray="${Math.round(p*201)} 201" transform="rotate(-90 40 40)" style="transition:stroke-dasharray .8s"/><text x="40" y="46" text-anchor="middle" font-size="17" font-weight="700" fill="currentColor">${t}</text></svg>`;
VIEWS.dash=()=>{const c=cfg(),on=k=>(c.cards.find(x=>x.k===k)||{}).on,hr=new Date().getHours(),du=dueItems(),dn=du.filter(x=>x.d).length,p=du.length?dn/du.length:0,nx=du.find(x=>!x.d),sc=score(er()),hb=D.habits.filter(x=>x.type!=='limit'),ad=hb.length?hb.reduce((a,x)=>{const s=hstat(x);return a+(s.n?s.a/s.n:0)},0)/hb.length:0,ws=add(T,-((dt(T).getDay()+1)%7));
 let o=`<div class="card sky"><div class="row"><div class="g"><div class="big">${hr<12?'صبح بخیر':hr<18?'روز بخیر':'شب بخیر'}${c.name?' '+H(c.name):''}</div><div class="mut">زندگی نو</div></div><span class="tag">Zendino · Life OS</span></div></div>`;
 if(c.next&&on('next'))o+=`<div class="card nx"><div class="mut">قدم بعدی</div><div class="big">${nx?H(nx.n):'همه‌چیز انجام شد'}</div><div class="row" style="margin-top:8px">${nx?`<button class="btn" onclick="${nx.f}">${nx.b||'انجام شد'}</button>`:''}<button class="btn o" onclick="go('due')">همه‌ی موعدها</button></div></div>`;
 if(on('tasks')||on('energy'))o+=`<div class="row st">`+(on('tasks')?`<div class="card g" style="text-align:center"><div class="mut" style="text-align:right">پیشرفت امروز</div>${ringSVG(p,'var(--acc)',fa(Math.round(p*100))+'٪')}<div class="mut">${fa(dn)} از ${fa(du.length)}</div></div>`:'')+(on('energy')?`<div class="card g" style="text-align:center" onclick="go('en')"><div class="mut" style="text-align:right">انرژی</div>${ringSVG(sc/5,'var(--acc2)',fa(sc.toFixed(1)))}<div class="mut">از ۵</div></div>`:'')+'</div>';
 if(on('habits'))o+=`<div class="card"><div class="row"><b class="g" onclick="go('hab')">عادت‌ها</b><span class="mut">${fa(Math.round(ad*100))}٪ پایبندی ۱۴ روز اخیر</span></div><div class="row" style="justify-content:space-between;margin-top:8px">${['ش','ی','د','س','چ','پ','ج'].map((l,i)=>{const k=add(ws,i),hs=hb.filter(h=>k<=iso()),n=hs.filter(h=>hdone(h,k)).length,s=!hs.length?0:n===hs.length?2:n>0?1:0;return `<div class="mut" style="text-align:center;font-size:12px"><div class="dot s${s}"></div>${l}</div>`}).join('')}</div></div>`;
 if(on('habits')&&D.habits.length)o+=`<div class="card"><h2>عادت‌های امروز</h2>${D.habits.map(habMini).join('')}</div>`;
 return o+c.cards.filter(x=>x.on&&CD[x.k]&&!['next','tasks','energy','habits'].includes(x.k)).map(x=>`<div class="card">${CD[x.k]()}</div>`).join('')};
VIEWS.more=()=>`<div class="card"><div class="row wrap">${[['hab','عادت‌ها'],['due','موعد امروز'],['mis','ماموریت‌ها'],['xp','XP و Achievement'],['sug','پیشنهادها'],['inc','درآمد'],['crm','مخاطبین'],['jr','ژورنال'],['rep','گزارش‌ها'],['srch','جست‌وجو'],['en','انرژی'],['ctl','مرکز کنترل']].map(([k,v])=>`<button class="btn o" style="flex:1 0 40%" onclick="go('${k}')">${v}</button>`).join('')}</div></div>`;
// نمودار روند
const trend=()=>{const ks=Array.from({length:14},(_,i)=>back(13-i)),a=ks.map(k=>doneIn([k])),e=ks.map(k=>{const r=D.energy.find(x=>x.id===k);return r?score(r):0}),ma=Math.max(1,...a),pl=(v,m,col)=>`<polyline fill="none" stroke="${col}" stroke-width="2.5" stroke-linejoin="round" points="${v.map((y,i)=>((13-i)/13*300).toFixed(1)+','+(66-y/m*58).toFixed(1)).join(' ')}"/>`;return `<div class="card"><h2>روند ۱۴ روز اخیر</h2><svg viewBox="0 0 300 70" width="100%" role="img" aria-label="نمودار خطی روند کارها و انرژی">${pl(a,ma,'var(--acc)')}${pl(e,5,'var(--acc2)')}</svg><div class="mut"><span style="color:var(--acc)">●</span> کار انجام‌شده · <span style="color:var(--acc2)">●</span> انرژی</div></div>`};
const _rp=VIEWS.rep;VIEWS.rep=()=>_rp()+trend();
const linkOf=v=>{const l=(v||'').split(':');return l[0]==='p'?{projectId:l[1],goalId:(D.projects.find(p=>p.id===l[1])||{}).goalId||null}:l[0]==='g'?{goalId:l[1],projectId:null}:{goalId:null,projectId:null}};
const linkOpts=cur=>'<option value="">بدون ارتباط</option>'+D.goals.map(g=>`<option value="g:${g.id}" ${cur==='g:'+g.id?'selected':''}>هدف: ${H(g.title)}</option>`).join('')+D.projects.map(p=>`<option value="p:${p.id}" ${cur==='p:'+p.id?'selected':''}>پروژه: ${H(p.title)}</option>`).join('');
const linkSel=h=>`<select aria-label="ارتباط با هدف یا پروژه" style="margin-top:4px;min-height:34px;font-size:12px" onchange="linkH('${h.id}',this.value)">${linkOpts(h.projectId?'p:'+h.projectId:h.goalId?'g:'+h.goalId:'')}</select>`;
async function linkH(id,v){const h=D.habits.find(x=>x.id===id);Object.assign(h,linkOf(v));await save('habits',h)}
const hp=h=>h.type==='limit'?Math.max(0,1-weekUsed(h,T)/(h.target||1)):(()=>{const s=hstat(h);return s.n?s.a/s.n:0})();
pp=p=>avg([...D.tasks.filter(t=>t.projectId===p.id).map(tp),...D.habits.filter(h=>h.projectId===p.id).map(hp)]);
gp=g=>avg([...D.projects.filter(p=>p.goalId===g.id).map(pp),...D.tasks.filter(t=>t.goalId===g.id&&!t.projectId).map(tp),...D.habits.filter(h=>h.goalId===g.id&&!h.projectId).map(hp)]);
const habMini=h=>{const l=HL(h,T),d=hdone(h,T),sk=l&&l.skip,tg=h.tag?` <span class="tag">${H(h.tag)}</span>`:'';
 if(h.type==='limit'){const u=weekUsed(h,T),over=u>h.target;return `<div class="it" style="display:block"><div class="row"><span class="g">${H(h.title)}${tg}</span><button class="btn o" onclick="limH('${h.id}',1)">＋۱</button></div><div class="bar" style="margin-top:4px"><i style="width:${Math.max(0,1-u/h.target)*100}%;background:${over?'#e5484d':'var(--ok)'}"></i></div><div class="mut">${fa(u)} از سقف ${fa(h.target)} این هفته</div></div>`}
 return `<div class="it"><span class="g ${d||sk?'mut':''}">${H(h.title)}${tg}${sk?' · رد شد':''}</span>${h.type==='daily'?`<button class="chk ${d?'on':''}" aria-label="ثبت ${H(h.title)}" onclick="logH('${h.id}',${d?0:1})">${d?'✓':''}</button>`:`<input type="number" min="0" style="width:84px" aria-label="مقدار" value="${l&&!l.skip?l.value:''}" placeholder="/${fa(h.target)}" onchange="logH('${h.id}',+nz(this.value))">`}</div>`};
render();
